# Generated by Django 4.2 on 2026-03-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_alter_property_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
