# Generated by Django 4.2 on 2026-03-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0005_alter_collection_id_alter_like_id_alter_property_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Full Address"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="distance_from_campus",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Distance from Campus"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
