# Generated by Django 4.2 on 2026-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_property_address_property_distance_from_campus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
